version: "3.3"

services:
    app:
        build:
            args:
                user: ${HOST_USER}
                uid: ${HOST_UID}
            context: .
            dockerfile: ./docker/Dockerfile
        env_file: ./src/.env
        restart: always
        volumes:
            - ./src:/home/${HOST_USER}/site
        networks:
            - cnccommunity

    nginx:
        image: nginx:stable-alpine
        restart: always
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./src:/home/${HOST_USER}/site
            - ./docker/nginx/templates:/etc/nginx/templates/
        environment:
            NGINX_ENVSUBST_TEMPLATE_SUFFIX: ".conf"
            HOST_USER: ${HOST_USER}
        networks:
            - cnccommunity

    mysql:
        image: mariadb:latest
        restart: always
        env_file: ./src/.env
        volumes:
            - ./docker/mysql/init:/docker-entrypoint-initdb.d
            - cnc-community-db:/var/lib/mysql
        networks:
            - cnccommunity

    db-backup:
        env_file: ./src/.env
        image: tiredofit/db-backup
        volumes:
            - ./backups:/backup
        restart: always
        links:
            - mysql
        networks:
            - cnccommunity

networks:
    cnccommunity:
        driver: bridge

volumes:
    cnc-community-db:
        driver: local
