version: "3.3"

services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    restart: unless-stopped
    working_dir: /home/laravel/site
    env_file:
      - ./src/.env
    volumes:
      - ./src:/home/laravel/site
    networks:
      - laravel

  mysql:
    image: mysql:5.7.29
    restart: unless-stopped
    env_file:
      - ./src/.env
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d
      - ./mysql:/var/lib/mysql
    networks:
      - laravel

  nginx:
    image: nginx:stable-alpine
    restart: unless-stopped
    ports:
      - "8080:80"
    env_file:
      - ./src/.env
    volumes:
      - ./src:/home/laravel/site
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    env_file:
      - ./src/.env
    environment:
      MYSQL_ROOT_PASSWORD: secret
      PMA_HOST: mysql
      PMA_PORT: 3306
    depends_on:
      - mysql
    ports:
      - "8081:80"
    volumes:
      - /sessions
    networks: 
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  phpmyadmin:
    driver: local
  mysql:
    driver: local